name: Deploy Snapshot

on:
  push:
    branches: [ 'master' ]

jobs:
  deploy:
    name: Deploy Snapshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Execute Gradle Build
        run: ./gradlew build -Pbuild.release=true
      - name: Publish Jars
        run: ./gradlew publish
        env:
          PUBLISH_TOKEN: ${{secrets.MAVEN_PUBLISH_TOKEN}}