name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Get Tag Name
        id: tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Execute Gradle Build
        run: ./gradlew build -Pbuild.release=true
      - name: Publish Jars
        run: ./gradlew publish
        env:
          PUBLISH_TOKEN: ${{secrets.MAVEN_PUBLISH_TOKEN}}
          VERSION: ${{steps.tag_name.outputs.VERSION}}